package com.archscope.jetbrains.render;

import java.util.Comparator;
import java.util.List;
import java.util.Map;

final class EnglishReportUi {
    private static final List<Map.Entry<String, String>> TRANSLATIONS = List.of(
            Map.entry("只展示能够绑定到所选提交或目标快照的行为、正确性、安全和设计边界问题。", "Only behavior, correctness, security, and design-boundary findings backed by the selected commits or target snapshot are shown."),
            Map.entry("每个提交与其第一父提交比较；这里解释所选提交如何共同形成目标架构。", "Each commit is compared with its first parent to explain how the selected commits form the target architecture."),
            Map.entry("当前证据没有形成可靠的正确性、安全或设计边界问题。", "The current evidence does not support a reliable correctness, security, or design-boundary finding."),
            Map.entry("这些输入彼此独立，在“", "These inputs are independent and join at \""),
            Map.entry("共同参与判断；点开步骤可查看每项源码。", "\" to participate in the decision. Open the step to inspect each source."),
            Map.entry("这里只保留源码证据尚不能可靠回答的内容。", "Only questions that cannot yet be answered reliably from source evidence remain here."),
            Map.entry("在下面的业务步骤中查看数据如何进入、变化和落地", "Follow the business steps below to see how data enters, changes, and is persisted"),
            Map.entry("在当前项目中打开源码", "Open source in the current project"),
            Map.entry("在当前工作区打开源码", "Open source in the current workspace"),
            Map.entry("该分支在这里结束", "This branch ends here"),
            Map.entry("外部/模型调用", "External/model call"),
            Map.entry("判断/旁支", "Decision/branch"),
            Map.entry("入口/控制", "Entry/control"),
            Map.entry("主数据流向", "Primary data direction"),
            Map.entry("模型调用", "Model call"),
            Map.entry("主路径", "Main path"),
            Map.entry("持久化", "Persistence"),
            Map.entry("旁支", "Branch"),
            Map.entry("判断", "Decision"),
            Map.entry("控制", "Control"),
            Map.entry("外部", "External"),
            Map.entry("模型", "Model"),
            Map.entry("调用", "Call"),
            Map.entry("入口", "Entry"),
            Map.entry("的完整业务旅程", " complete business journey"),
            Map.entry("没有可确认的主流程", "No confirmed primary flow"),
            Map.entry("白话走一遍", "Plain-language walkthrough"),
            Map.entry("异常出口", "Exception exits"),
            Map.entry("业务调用方", "Business caller"),
            Map.entry("业务请求", "Business request"),
            Map.entry("业务处理", "Business processing"),
            Map.entry("进入系统", "enters the system"),
            Map.entry("返回结果", "returns the result"),
            Map.entry("返回给", "Return to"),
            Map.entry("流程终止", "Flow stops"),
            Map.entry("主数据", "Primary data"),
            Map.entry("发起", "Ingress"),
            Map.entry("处理", "Process"),
            Map.entry("返回", "Return"),
            Map.entry("响应", "Response"),
            Map.entry("在这里落地", "Persisted here"),
            Map.entry("没有可解析的源码节点，结论应视为待确认", "No source node could be resolved; treat this conclusion as unconfirmed"),
            Map.entry("本流程只跟踪一条主数据故事", "This flow follows one primary data story"),
            Map.entry("辅助输入汇入", "Supporting inputs"),
            Map.entry("汇入步骤", "join step"),
            Map.entry("辅助输入", "Supporting input"),
            Map.entry("后续独立消费", "Later independent consumers"),
            Map.entry("独立流程", "Independent flow"),
            Map.entry("主数据流", "Primary data flow"),
            Map.entry("一次看清触发如何分流", "How the trigger routes into separate flows"),
            Map.entry("关键业务对象与字段", "Key business objects and fields"),
            Map.entry("待确认与补充记录", "Open questions and evidence updates"),
            Map.entry("该步骤仅用于定位本次改动", "This step only provides context for locating the change"),
            Map.entry("展开、补充或修正当前报告", "Expand, supplement, or correct this report"),
            Map.entry("本次提交在业务流程中的位置", "Where this change sits in the business flow"),
            Map.entry("未发现可证实问题", "No evidence-backed findings"),
            Map.entry("无已确认前置条件", "No confirmed preconditions"),
            Map.entry("已由补充源码确认", "Confirmed by additional source evidence"),
            Map.entry("模型没有给出业务流程", "The model did not return a business flow"),
            Map.entry("请在 IDE 报告编辑器中继续分析", "Continue the analysis in the IDE report editor"),
            Map.entry("当前实现限制", "Current implementation limitations"),
            Map.entry("目标快照下的结果", "Outcome in the target snapshot"),
            Map.entry("只看本次改动", "Show this change only"),
            Map.entry("先用白话走一遍", "Plain-language walkthrough"),
            Map.entry("没有可确认的业务域", "No confirmed business domains"),
            Map.entry("没有待确认问题", "No open questions"),
            Map.entry("没有提交演进数据", "No commit evolution data"),
            Map.entry("正在补充分析", "Updating the analysis"),
            Map.entry("已应用 System Prompt", "System Prompt applied"),
            Map.entry("默认系统提示词", "Default system prompt"),
            Map.entry("默认提示词", "Default instructions"),
            Map.entry("模型未记录", "Model not recorded"),
            Map.entry("业务域总览", "Business domain overview"),
            Map.entry("业务流程节点", "Business flow step"),
            Map.entry("完整业务流程", "Complete business flow"),
            Map.entry("完整路径", "Complete path"),
            Map.entry("完整流程", "Complete flows"),
            Map.entry("代码审核发现", "Code review findings"),
            Map.entry("提交演进", "Commit evolution"),
            Map.entry("改动定位", "Change location"),
            Map.entry("审核发现", "Review findings"),
            Map.entry("证据审核", "Evidence review"),
            Map.entry("证据收敛", "Evidence convergence"),
            Map.entry("单轮 SOP", "Single SOP"),
            Map.entry("证据边界", "Evidence boundary"),
            Map.entry("报告生成", "Report generation"),
            Map.entry("规划", "Planning"),
            Map.entry("业务总览", "Business overview"),
            Map.entry("业务上下文", "Business context"),
            Map.entry("业务影响", "Business impact"),
            Map.entry("业务结果", "Business outcome"),
            Map.entry("业务规则", "Business rules"),
            Map.entry("业务术语", "Business terms"),
            Map.entry("域间关系", "Domain relationships"),
            Map.entry("业务指标", "Business metrics"),
            Map.entry("业务内容", "Business content"),
            Map.entry("业务流程", "Business flow"),
            Map.entry("业务域", "Business domains"),
            Map.entry("职责模块", "Responsibility module"),
            Map.entry("代码边界", "Code boundary"),
            Map.entry("跨模块契约", "Cross-module contract"),
            Map.entry("源码证据", "Source evidence"),
            Map.entry("源码方法", "Source methods"),
            Map.entry("源码取证", "Source inspection"),
            Map.entry("源码", "Source"),
            Map.entry("失败与退出", "Failures and exits"),
            Map.entry("失败退出", "Failure exit"),
            Map.entry("失败", "Failure"),
            Map.entry("提交补充分析", "Submit follow-up analysis"),
            Map.entry("继续分析", "Continue analysis"),
            Map.entry("选择业务流程", "Select business flow"),
            Map.entry("切换主题", "Toggle theme"),
            Map.entry("恢复 100%", "Reset to 100%"),
            Map.entry("缩小", "Zoom out"),
            Map.entry("放大", "Zoom in"),
            Map.entry("显示详情", "Show details"),
            Map.entry("关闭详情", "Close details"),
            Map.entry("提交改动", "Commit changes"),
            Map.entry("改动产生的结果", "Result of the change"),
            Map.entry("改动结果已定位", "Change outcome located"),
            Map.entry("流程分析完成", "Flow analysis complete"),
            Map.entry("流程在这里结束", "The flow ends here"),
            Map.entry("分析入口", "Analysis entry"),
            Map.entry("目标快照", "Target snapshot"),
            Map.entry("所选提交", "Selected commits"),
            Map.entry("直接改动", "Direct changes"),
            Map.entry("行为受影响", "Behavior affected"),
            Map.entry("已解释文件", "Explained files"),
            Map.entry("未进入主流程", "Outside the primary flow"),
            Map.entry("设计主张", "Design principles"),
            Map.entry("状态与事件", "State and events"),
            Map.entry("状态变化", "State changes"),
            Map.entry("本步数据来去", "Data entering and leaving this step"),
            Map.entry("本步数据变化", "Data changes in this step"),
            Map.entry("数据汇入", "Data inputs"),
            Map.entry("数据变化", "Data transformation"),
            Map.entry("数据读写", "Data reads and writes"),
            Map.entry("读取数据", "Data read"),
            Map.entry("写入数据", "Data written"),
            Map.entry("下游消费者", "Downstream consumers"),
            Map.entry("主数据进入", "Primary data enters"),
            Map.entry("核心业务数据", "Primary business data"),
            Map.entry("业务数据", "Business data"),
            Map.entry("控制条件汇入", "Control input joins"),
            Map.entry("配置条件汇入", "Configuration input joins"),
            Map.entry("辅助数据汇入", "Supporting data joins"),
            Map.entry("查询补充数据", "Lookup data"),
            Map.entry("稍后独立读取", "Read later in an independent execution"),
            Map.entry("不属于本次执行", "Outside this execution"),
            Map.entry("前置条件", "Preconditions"),
            Map.entry("触发条件", "Trigger"),
            Map.entry("进入此流程", "Flow routing condition"),
            Map.entry("参与者", "Actor"),
            Map.entry("负责并产出", "Owns and produces"),
            Map.entry("明确不负责", "Explicitly does not own"),
            Map.entry("负责什么", "Responsibilities"),
            Map.entry("传输对象", "Payload"),
            Map.entry("生命周期待确认", "Lifecycle unconfirmed"),
            Map.entry("修改前", "Before"),
            Map.entry("修改后", "After"),
            Map.entry("修改原因", "Reason for change"),
            Map.entry("未提供修改前说明", "No before-change description"),
            Map.entry("未提供修改后说明", "No after-change description"),
            Map.entry("架构影响：", "Architecture impact:"),
            Map.entry("未命名流程", "Unnamed flow"),
            Map.entry("待确认模块", "Unconfirmed module"),
            Map.entry("说明待确认", "Description unconfirmed"),
            Map.entry("来源待确认", "Source unconfirmed"),
            Map.entry("独立职责", "Independent responsibility"),
            Map.entry("补充记录", "Evidence updates"),
            Map.entry("已折叠", "Collapsed"),
            Map.entry("个业务上下文步骤", "business context steps"),
            Map.entry("个来源按源码顺序汇入", "sources join in source order"),
            Map.entry("个提交", "commits"),
            Map.entry("默认提示词", "Default instructions"),
            Map.entry("耗时未知", "Duration unknown"),
            Map.entry("耗时", "Duration"),
            Map.entry("小时", "h"),
            Map.entry("分", "m"),
            Map.entry("秒", "s"),
            Map.entry("本次修改", "Changed"),
            Map.entry("受影响", "Affected"),
            Map.entry("业务上下文", "Context"),
            Map.entry("待确认", "Unconfirmed"),
            Map.entry("已确认", "Confirmed"),
            Map.entry("接收", "Receives"),
            Map.entry("产出", "Produces"),
            Map.entry("负责", "Owns"),
            Map.entry("协作", "Collaborates"),
            Map.entry("状态", "Status"),
            Map.entry("时间", "Time"),
            Map.entry("规则", "Rule"),
            Map.entry("字段", "Fields"),
            Map.entry("数据", "Data"),
            Map.entry("其他", "Other"),
            Map.entry("来源：", "Source:"),
            Map.entry("来源", "Source"),
            Map.entry("读取：", "Reads:"),
            Map.entry("写入：", "Writes:"),
            Map.entry("存储：", "Storage:"),
            Map.entry("转换：", "Transformation:"),
            Map.entry("去向：", "Destination:"),
            Map.entry("去向", "Destination"),
            Map.entry("用户：", "User:"),
            Map.entry("系统：", "System:"),
            Map.entry("的内部流程", " internal flow"),
            Map.entry("分支", "Branch"),
            Map.entry("成功", "Success"),
            Map.entry("取消", "Cancel"),
            Map.entry("继续", "Continue"),
            Map.entry("保持原样", "Unchanged"),
            Map.entry("不变", "Unchanged"),
            Map.entry("创建", "Created"),
            Map.entry("未创建", "Not created"),
            Map.entry("增加", "Increased"),
            Map.entry("减少", "Decreased"),
            Map.entry("清理", "Cleared"),
            Map.entry("已产生事件", "Event emitted"),
            Map.entry("未产生事件", "No event emitted"),
            Map.entry("身份标识", "Identity"),
            Map.entry("传递", "Transfer"),
            Map.entry("流转", "Flow"),
            Map.entry("进入", "Ingest"),
            Map.entry("校验", "Validate"),
            Map.entry("转换", "Transform"),
            Map.entry("落地", "Persist"),
            Map.entry("交付", "Deliver"),
            Map.entry("触发", "Trigger"),
            Map.entry("结果：", "Outcome: "),
            Map.entry("关联关系", "Relationship"),
            Map.entry("结束", "End"),
            Map.entry("流程控制", "Flow control"),
            Map.entry("当前步骤", "Current step"),
            Map.entry("本步", "This step"),
            Map.entry("当前", "Current"),
            Map.entry("另", "Another"),
            Map.entry("再读取", "Then read"),
            Map.entry("先读取", "Read first"),
            Map.entry("最后读取", "Read last"),
            Map.entry("随后读取", "Read next"),
            Map.entry("项", "items")
    ).stream().sorted(Comparator.comparingInt((Map.Entry<String, String> entry) -> entry.getKey().length()).reversed()).toList();

    private EnglishReportUi() {
    }

    static String translate(String html) {
        String translated = html.replace("<html lang=\"zh-CN\">", "<html lang=\"en\">");
        for (Map.Entry<String, String> entry : TRANSLATIONS) {
            translated = translated.replace(entry.getKey(), entry.getValue());
        }
        return translated;
    }
}
